spring:
  profiles:
    active: prod
server:
  port: 8761

eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
  client:
    #表示是否将自己注册到Eureka Server
    registerWithEureka: false
    #表示是否从Eureka Server获取注册信息
    fetchRegistry: false
    #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔
    serviceUrl.defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
---
spring:
  profiles: peer1

server:
  port: 8761

eureka:
  instance:
    preferIpAddress: true
    hostname: peer1
  client:
    #表示是否将自己注册到Eureka Server
    registerWithEureka: false
    #表示是否从Eureka Server获取注册信息
    fetchRegistry: false
    #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔
    serviceUrl.defaultZone: http://peer2:8762/eureka/

---
spring:
  profiles: peer2

server:
  port: 8762

eureka:
  instance:
    preferIpAddress: true
    hostname: peer2
  client:
    #表示是否将自己注册到Eureka Server
    registerWithEureka: false
    #表示是否从Eureka Server获取注册信息
    fetchRegistry: false
    #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔
    serviceUrl.defaultZone: http://peer1:8761/eureka/

---