spring:
  profiles:
    active: prod
server:
  port: 8761

eureka:
  instance:
  preferIpAddress: true
    #hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    #serviceUrl.defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
---
spring:
  profiles: dev

server:
  port: 8080

---
spring:
  profiles: test

server:
  port: 8081

---